---
- name: ansible script for deploying application into remote server
  hosts: dest_server
  tasks:
    - name: copy application to the remote server
      copy:
        src: /var/lib/jenkins/workspace/pipeline_cloneanddeployjar/target/spring-petclinic-2.7.3.jar
        dest: /root/

    - name: start the application in the remote server
      shell: nohup java -jar /root/spring-petclinic-2.7.3.jar & 1>&2 > /dev/null
